### ISSUE TITLE
SSW 345 HW Task Tracker

### ISSUE THREAD

**Issue by m0hamedb3ngab5ia** [mohamedbengabsia/SSW345#1]
## Homework Task List

Assignment 1
- [x] Complete part I of Assignment 1 - Create Latex book for HW - create "team" and "Github HW" chapters
- [x] Complete part II of Assignment 1 - Solve git learning course (complete 5 levels)
- [x] Complete part III of Assignment 1 - Create issue in github for homework task list
